/*
 * generated by Xtext
 */
package de.beyondjava.xtext.jsf.ui.contentassist

import de.beyondjava.xtext.jsf.ui.contentassist.AbstractComponentLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ComponentLanguageProposalProvider extends AbstractComponentLanguageProposalProvider {
}
