/*
 * generated by Xtext
 */
package de.beyondjava.xtext.jsf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ComponentLanguageUiModule extends de.beyondjava.xtext.jsf.ui.AbstractComponentLanguageUiModule {
	public ComponentLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
