/*
 * generated by Xtext
 */
package de.beyondjava.xtext.jsf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComponentLanguageRuntimeModule extends de.beyondjava.xtext.jsf.AbstractComponentLanguageRuntimeModule {

}
